modLoader="javafml" 
loaderVersion="[38,)"
license="MIT"
issueTrackerURL="https://github.com/VsnGamer/ElevatorMod/issues/"
logoFile="logo.png"
[[mods]]
modId="elevatorid"
version="${file.jarVersion}"
displayName="Elevator Mod"
#updateJSONURL="http://myurl.me/"
displayURL="https://minecraft.curseforge.com/projects/openblocks-elevator/"
credits="OpenBlocks Team, Paint_Ninja for porting to 1.18"
authors="VsnGamer"
description='''
Simple port of the elevator from OpenBlocks to 1.8+
'''
[[dependencies.elevatorid]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.elevatorid]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"